
from typing import Union, Optional, List
from urllib import response
from fastapi import FastAPI, Request, File, UploadFile, status

from fastapi.responses import HTMLResponse, RedirectResponse, FileResponse, Response
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates

app = FastAPI()

app.mount("/static", StaticFiles(directory="static"), name="static")


templates = Jinja2Templates(directory="templates")

some_file_path = "static/images/J&E_Abby_Wedding-72y128x-1.png"



@app.get("/")
async def main():
    return FileResponse(some_file_path)


# @app.get(
#     "/image",

#     # Set what the media type will be in the autogenerated OpenAPI specification.
#     # fastapi.tiangolo.com/advanced/additional-responses/#additional-media-types-for-the-main-response
#     responses = {
#         200: {
#             "content": {"image/png": {}}
#         }
#     }, response_class=Response)
# def get_image():
#     image_bytes: bytes = generate_cat_picture()
#     # media_type here sets the media type of the actual response sent to the client.
#     return Response(content=image_bytes, media_type="image/png")